### ISSUE TITLE
Plugin uses option "sortByTitle" which does not exist

### ISSUE THREAD

**Issue by mrclschstr** [cosmocode/simplenavi#16]
Long story short: This plugin looks for an option `sortByTitle` which does not exist:

https://github.com/cosmocode/simplenavi/blob/9856694b8a9c8d03b256ae91e4d05836e3c4b92c/syntax.php#L53

Maybe https://github.com/cosmocode/simplenavi/pull/11 is a possible solution?

**Comment by splitbrain** [comment]
fixed with recent refactoring
