### ISSUE TITLE
Hide sidebar-page in navigation

### ISSUE THREAD

**Issue by natrius** [cosmocode/simplenavi#18]
I really like this plugin, it looks good, but it does also show the "sidebar" page in the menu, is it possible to hide it?
I could not find an option for something like that.

**Comment by dennisverspuij** [comment]
You can use [hidepage](https://www.dokuwiki.org/config:hidepages) for this.

**Comment by sergey-inform** [comment]
Not very useful if someone wants to keep sidebar-pages in '?do=index' but hide them in navigation menus.

Simple patch:
```
          }elseif(noNS($id) == $conf['start']){
              // skip the main start page
              return false;
+        }elseif(noNS($id) == $conf['sidebar']){
+            // hide sidebar pages
+            return false;
         }
```

**Comment by Mibran** [comment]
Changing line 104 helped, new code:

`}elseif($type == 'f' && ((strlen($file)>10 && substr($file,-11) == 'sidebar.txt') || !empty($opts['nofiles']) || substr($file,-4) != '.txt' )){`
