### ISSUE TITLE
First  indentation

### ISSUE THREAD

**Issue by plabanowski** [cosmocode/simplenavi#22]
Hello,

the first indentation when opening a branch does not work. The objects are placed directly under the parent. This behaviour makes the visual aspect confusing.

thx

**Comment by pkgzm** [comment]
You probably need to upgrade your plugins (bootstrap3) because the visualization is managed into a CSS file that is not included into the simplenavi plugin.

**Comment by plabanowski** [comment]
You're right. By modifying the bootstrap css it solved my problem.
