### ISSUE TITLE
Add an option to list pages before the namespaces

### ISSUE THREAD

**Issue by rodrigor** [cosmocode/simplenavi#25]
Before: 
<img src="https://user-images.githubusercontent.com/288272/81936298-69d84380-95c8-11ea-875d-a55959188c6a.png">

After:
<img src="https://user-images.githubusercontent.com/288272/81936329-78bef600-95c8-11ea-94c5-0d7ecad20779.png">

**Comment by splitbrain** [comment]
The plugin now supports either namespaces first, or namespaces and pages mixed. Pages first is not planned.
