### ISSUE TITLE
Expand Namespaces/Subnamespaces

### ISSUE THREAD

**Issue by ccarlo88** [cosmocode/simplenavi#29]
Hello,

Today, each time we want to go to a subsection, we need to click in one namespace and then navigate to the next one.
Do you think an expanding option is feasible?

![image](https://user-images.githubusercontent.com/59994318/108988024-43395400-7694-11eb-9982-3a10fc295f15.png)

Thanks!

**Comment by splitbrain** [comment]
out of scope for this plugin
