### ISSUE TITLE
Wrong rendering if the name of namespace matches page name

### ISSUE THREAD

**Issue by DelPoint** [cosmocode/simplenavi#5]
Hi Gents,

I've found a little annoying problem with the rendering order (LI & UL elements) of sub-namespaces.
Condition of the problem: the name of a sub-namespace matches the name of a page.
### Consider the following namespaces:

[[**test:**first]]
[[**test:**second]]
[[**test:**second:first]]
[[**test:**third]]

[[**second:**first]]
[[**second:**second]]

<i>Note:</i> the name of 2nd level sub-namespace (test -> second) matches the name of the 1st level "second" namespace.
#### The list items ought to be rendered in alphabetical order as follows:

<ul>
  <li><b>second-></b>
    <ul>
      <li>second:first</li>
      <li>second:second</li>
    </ul>
  </li>
</ul>
  

<ul>
  <li><b>test-></b>
    <ul>
      <li>test:first</li>
      <li>test:second->
        <ul>
          <li>test:second:first</li>
        </ul>
      </li>
      <li>test:third</li>
    </ul>
  </li>
</ul>

##### a) IF any page opened in "test" namespace:

![image1](https://cloud.githubusercontent.com/assets/1571585/7505806/7148613a-f457-11e4-9625-32909ac58ea1.png)
Notice the "second:second" **page** is displayed as first item instead of "second" **namespace**.
##### b) IF any page opened in "second" 1st level namespace:

![image2](https://cloud.githubusercontent.com/assets/1571585/7505805/7147ed18-f457-11e4-93f3-b3387ea7e8a0.png)
Notice the missing sub-menu for "second" **namespace**, and as page names from "second" namespace are displayed in reverse order as 1st level items instead of 2nd level items of "second" namespace.

The problem is caused - IMHO - by the fact that a name of a 1st level namespace matches a name of a page name:
- "second" page name [[test:second]] or [[second:second]] matches to "second" of [[second:]] namespace.

Hope I could clearly demonstrate the issue.

Ciao,
DelD.

**Comment by majnu-campact** [comment]
+1

**Comment by DelPoint** [comment]
It seems to me the issue is gone in Detritus release. Thx.

**Comment by DelPoint** [comment]
Sorry, but I have to reopen this. After carefully tested in the latest version, only the above mentioned case **b.)** changed as follows:
- reverse order gone
- this case displays identical results as case a.) - ie. it doesn't matter anymore whether the page shown from a sub-namespace (child) or from a higher, parent namespace

Case **a.)** still remains as in my initial report.

DelD.

**Comment by rogyw** [comment]
+1 For issue with child page shown in previous namespace in menu of a new install.

To clarify, in my case (simplified):
Structure is:
- mike:mike
- mike:page_a
- playground:playground
- playground:test_page_1
- romeo:romeo
- romeo:alpha1
- romeo:bravo2
- romeo:test3
- Sidebar
- Syntax

When I open any file in namespace romeo the menu structure shown is:

* mike
* playground
  * alpha1
  * bravo2 
* romeo
  * test3
* side bar
* syntax

It appears that any page name I add within romeo which has a sort order before the sub page name romeo is shown above the romeo heading and any page name with sort order after romeo is shown below the main heading. This would be ok if there was a line or other visual clue from romeo namespace to each of the sub pages (above and below) - but in pure text form it doesn't seem to make sense to the end users as is.

**Comment by mrclschstr** [comment]
:+1:

**Comment by splitbrain** [comment]
this should be fixed with the recent refactoring
