### ISSUE TITLE
Sort namespaces by headline of start-page

### ISSUE THREAD

**Issue by igittigitt** [cosmocode/simplenavi#8]
Namespace lists are currently ordered by their namespace. This leads to strange results, if the option "use_heading" is set and headings differ from namespace-name.

To avoid this, the use_heading option should be honored and if set, the list should be sorted (natural oder ascii) by the headlines of the namespaces start-page.

**Comment by igittigitt** [comment]
Hmm, maybe i made a mistake. As i told above the simplenavi should order the list by namespace startpage title if the "use_heading" option is set. What i made in my pull request was making this a separate option.
I think it would be better to void the extra option an use the global setting for using headings. What do you think?

**Comment by mrclschstr** [comment]
Any update on this? Would really appreciate an update :smiley:

**Comment by splitbrain** [comment]
fixed with recent refactoring
